import "./globals.css";
import { Toaster } from "react-hot-toast";
import QueryProvider from "../app/Providers/QueryProvider";

export const metadata = {
  title: "SMS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <Toaster position="top-right" />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}